### ISSUE TITLE
Bower would not install graph-sdk until i changed the address

### ISSUE THREAD

**Issue by ConlanMcNamee** [OfficeDev/O365-Angular-Unified-API-Connect#13]
When running bower install off a cloned version, on Mac incase it makes a difference, bower hangs up on installing graph-sdk. Exact error included below
Failed to execute "git ls-remote --tags --heads git@github.com:microsoftgraph/msgraph-sdk-javascript.git", exit code of #128 Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Additional error details:
Permission denied (publickey).
fatal: Could not read from remote repository.

Once i changed the address to 
https://github.com/microsoftgraph/msgraph-sdk-javascrip.git
it worked properly.

**Comment by DianeD** [comment]
Hi @ConlanMcNamee . Thanks for reporting this issue, but did you mean to open it on the [SDK Connect sample](https://github.com/microsoftgraph/angular-connect-sample/issues/)? (This is the REST version.) We'll get that updated soon, thanks!

**Comment by ConlanMcNamee** [comment]
hmm yes probably, thanks!

**Comment by DianeD** [comment]
[Fixed](https://github.com/microsoftgraph/angular-connect-sample/commit/4471f4e41ae7c6a988daaaef646710c6fd519783)
Thanks again @ConlanMcNamee !
