### ISSUE TITLE
getting a 401 Unauthorized on https://graph.microsoft.com/v1.0/me

### ISSUE THREAD

**Issue by kcferguson1** [OfficeDev/O365-Angular-Unified-API-Connect#14]
angular.js:10514 GET https://graph.microsoft.com/v1.0/me 401 (Unauthorized)

**Comment by DianeD** [comment]
Hi @kcferguson1 . Thanks for reporting this issue. I did a fresh download, install, and app registration, but the sample works for me with personal and work accounts. 

Are you being prompted to consent for **Sign you in and read your profile** and **Send mail as you**?

**Comment by kcferguson1** [comment]
i got that on the first try and consented, the i get the error.

**Comment by DianeD** [comment]
Are you getting any additional error info in the response body? You can check on the Network tab of the browser developer tools, or in Fiddler. For example, here's the error I got after I removed the User.Read permission from the sample:

![image](https://cloud.githubusercontent.com/assets/8431452/21941244/a8a1c4f8-d97c-11e6-804b-acfc00d7e892.png)

If not, can you please try these troubleshooting steps?
Using the same account , log into [Graph explorer](https://graph.microsoft.io/graph-explorer) and see if the https://graph.microsoft.com/v1.0/me request works there. If it doesn't, can you provide the full Response body?

Capture the access token, paste it in http://jwt.io, and check that the "scp" parameter grants "Mail.Send User.Read" access. To capture the token, you can use Fiddler, the Network tab in the browser dev tools, or put a breakpoint in aad.js on line 33.

Provide the request id and date of the failing request? You can get it in from dev tools or Fiddler.

![image](https://cloud.githubusercontent.com/assets/8431452/21941345/3711a28a-d97d-11e6-85be-ef321c87c7a6.png)

**Comment by DianeD** [comment]
Hi @kcferguson1 . Closing this issue, but please reopen it if you're still having problems.

**Comment by ravirajesh** [comment]
HI... i am getting the error...403 Forbidden error for some of the mail id's when i try https://graph.microsoft.com/v1.0/me api....but for some of the mail id's i am able to get the basic profile details...any suggestions appreciated...

![capture](https://user-images.githubusercontent.com/18375942/35909674-49dc31c0-0c1a-11e8-8602-c724d8eba70c.PNG)
