### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by supraja1024** [OfficeDev/O365-Angular-Unified-API-Connect#18]
Downloaded the sample and changed the client_id with respect to my app and enabled permissions for the app in azure portal. It throws **401 Unauthorized** error when trying to send mail. 
Note : Enabled permissions for **send.mail** and user.read as mentioned

**Comment by jamescro** [comment]
This sample uses dynamic permissions, so you shouldn't need to set permissions in the Azure portal. Are you using the app registration portal linked in the readme (https://apps.dev.microsoft.com/)?
Also, did you ever see a consent screen that prompted you to approve the permissions that the sample needs when you authenticated?

**Comment by jamescro** [comment]
Closing for now. Please reopen if you continue to see the issue.
