### ISSUE TITLE
MICROSOFT GRAPH API...403 FORBIDDEN....https://graph.microsoft.com/v1.0/me

### ISSUE THREAD

**Issue by ravirajesh** [OfficeDev/O365-Angular-Unified-API-Connect#20]
HI... i am getting the error...403 Forbidden error for some of the mail id's when i try https://graph.microsoft.com/v1.0/me api....but for some of the mail id's i am able to get the basic profile details...any suggestions appreciated...

![capture](https://user-images.githubusercontent.com/18375942/35909674-49dc31c0-0c1a-11e8-8602-c724d8eba70c.PNG)

**Comment by jasonjoh** [comment]
We are archiving this sample as it is no longer being maintained. We're replacing it with a new sample which you can find here: https://github.com/microsoftgraph/msgraph-training-angularspa
